job: extension
config:
  name: my_first_flux_lora_v1
  process:
  - type: sd_trainer
    training_folder: mahabharat_experiment_output
    performance_log_every: 1000
    device: cuda:0
    trigger_word: MBHT
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 4
      push_to_hub: false
    datasets:
    - folder_path: /Users/ajinkyak/Codes/PROJECTS/mahabharat-image-gen/ai-toolkit/image_datasets
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
      - 1024
    train:
      batch_size: 1
      steps: 2000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0001
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-schnell
      is_flux: true
      quantize: true
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 1024
      height: 1024
      prompts:
      - woman with red hair, playing chess at the park, bomb going off in the background
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 20
meta:
  name: '[mahabharata_experiment]'
  version: '1.0'
